<?php
require_once 'PHPUnit/Framework.php';

// set up include path
set_include_path(
    realpath(dirname(__FILE__) . '/../src') . PATH_SEPARATOR
    . realpath(dirname(__FILE__) . '/../lib/ezcomponents-instantsvc/components') . PATH_SEPARATOR
    //. realpath(dirname(__FILE__) . '/../lib/ezcomponents') . PATH_SEPARATOR
    . get_include_path() . PATH_SEPARATOR
    . realpath(dirname(__FILE__) . '/../lib/pear')
);

// configure eZ Components autoloader
// required because of PHPCallGraphCli using eczConsoleTools
// and PHPCallGraph leveraging InstantSVC CodeAnalyzer and Extended Reflection API
require_once 'autoload-ezcomponents.php';

require_once 'PHPCallGraphCli.php';

/**
 * Test class for PHPCallGraphCli.
 * Generated by PHPUnit on 2009-05-06 at 21:36:06.
 */
class PHPCallGraphCliTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    PHPCallGraphCli
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new PHPCallGraphCli;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function getCommandLines() {
        $commandLines = array(
            // needs output buffering: array('--help', ''),
        );
        $optionSets = array(
            '',
            '-p',
            '-n',
            '-d',
        );
        // TODO: test different output drivers
        $argumentSets = array(
            'testfiles',
        );

        foreach ($optionSets as $optionSet) {
            foreach ($argumentSets as $argumentSet) {
                $commandLines[] = array($optionSet, $argumentSet);
            }
        }
        return $commandLines;
    }

    /**
     * @dataProvider getCommandLines
     */
    public function testRun($options, $arguments) {
        $outputDir = dirname(__FILE__) . '/output';
        if (!file_exists($outputDir)) {
            mkdir($outputDir, 0766, true);
        }
        $outputFileName = "phpcallgraph $options -- " . preg_replace('/[^-.+A-Za-z0-9]/', '_', $arguments) . '.txt';
        $outputFile = $outputDir . '/' . $outputFileName;
        $_SERVER["argv"] = explode(' ', $options);
        $_SERVER["argv"][] = '-o';
        $_SERVER["argv"][] = $outputFile;
        $_SERVER["argv"][] = '--';
        $_SERVER["argv"] = array_merge($_SERVER["argv"], explode(' ' . dirname(__FILE__) . '/' , dirname(__FILE__) . '/' . $arguments));
        //var_dump($_SERVER["argv"]);
        $this->object->run();
        $actual = file_get_contents($outputFile);
        $expectedFile = "$outputDir/.svn/text-base/$outputFileName.svn-base";
        $expected = file_get_contents($expectedFile);
        $this->assertEquals($expected, $actual);
    }
}
?>
